"""
Unit tests for data acquisition and quantitative report generation scripts.

Tests cover:
- Kelly criterion edge cases (flat returns, 100% win rate, win + push)
- Candle closing timestamp calculations (including 1M calendar months and leap years)
- Resample unclosed bar filtering (--tf 1M --resample 1M regression, 1W, 3D)
"""

from datetime import datetime, timezone
import unittest
from unittest.mock import MagicMock
import pandas as pd
from pathlib import Path
import tempfile

from scripts.data.fetch_binance import (
    get_candle_close_ms,
    get_resampled_bar_close_ms,
    resample_ohlcv,
)
from scripts.generate_asset_report import analyze_crypto
from scripts.test_strategy_dip_buy import run_dip_buy_test


class TestKellyCriterion(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.csv_path = Path(self.temp_dir.name) / "test_data.csv"

    def tearDown(self):
        self.temp_dir.cleanup()
        # Clean up any reports generated by dip buy test
        for f in Path("research/reports").glob("TEST_Strategy_DipBuy_*.md"):
            try:
                f.unlink()
            except OSError:
                pass

    def test_kelly_zero_returns(self):
        """All returns 0% (flat/ties) must yield Kelly 0.00%, NOT 100%."""
        df = pd.DataFrame({
            "datetime": pd.date_range("2020-01-01", periods=1000, freq="D"),
            "open": 100.0,
            "high": 100.0,
            "low": 100.0,
            "close": 100.0,
            "volume": 1000.0,
        })
        df.to_csv(self.csv_path, index=False)

        report, _ = analyze_crypto("TEST", self.csv_path, hold_days=365)
        self.assertIn("| **勝率 (Win Rate)** | **0.00%**", report)
        self.assertIn("| **標準策略 (基於平均值)** | `0.00%`", report)
        self.assertIn("| **盈虧比 (Reward/Risk)** | **0.00**", report)

        report_dip = run_dip_buy_test("TEST", self.csv_path, hold_days=365, threshold_pct=0.1)
        self.assertIn("| **勝率 (Win Rate)** | **0.00%**", report_dip)
        self.assertIn("| **標準策略 (基於平均值)** | `0.00%`", report_dip)

    def test_kelly_100pct_win_rate(self):
        """100% win rate must yield Kelly 100.00% and infinite odds."""
        df = pd.DataFrame({
            "datetime": pd.date_range("2020-01-01", periods=1000, freq="D"),
            "open": 100.0,
            "high": 100.0,
            "low": 100.0,
            "close": [100.0 + i for i in range(1000)],
            "volume": 1000.0,
        })
        df.to_csv(self.csv_path, index=False)

        report, _ = analyze_crypto("TEST", self.csv_path, hold_days=365)
        self.assertIn("| **勝率 (Win Rate)** | **100.00%**", report)
        self.assertIn("| **標準策略 (基於平均值)** | `100.00%`", report)
        self.assertIn("| **盈虧比 (Reward/Risk)** | **∞ (無虧損)**", report)

        report_dip = run_dip_buy_test("TEST", self.csv_path, hold_days=365, threshold_pct=10.0)
        self.assertIn("| **勝率 (Win Rate)** | **100.00%**", report_dip)
        self.assertIn("| **標準策略 (基於平均值)** | `100.00%`", report_dip)

    def test_kelly_win_and_ties(self):
        """When returns are win or tie (no losses), Kelly should equal prob_win."""
        prices = [100.0] * 500 + [100.0 + i for i in range(500)]
        df = pd.DataFrame({
            "datetime": pd.date_range("2020-01-01", periods=1000, freq="D"),
            "open": 100.0,
            "high": prices,
            "low": 100.0,
            "close": prices,
            "volume": 1000.0,
        })
        df.to_csv(self.csv_path, index=False)

        report, _ = analyze_crypto("TEST", self.csv_path, hold_days=365)
        self.assertIn("| **賠率 (Loss Rate)** | 0.00%", report)
        self.assertIn("| **盈虧比 (Reward/Risk)** | **∞ (無虧損)**", report)


class TestFetchBinanceCandleClose(unittest.TestCase):
    def setUp(self):
        self.mock_exchange = MagicMock()
        self.mock_exchange.parse_timeframe.side_effect = lambda tf: {
            "1m": 60,
            "1h": 3600,
            "1d": 86400,
            "1w": 604800,
            "1M": 2592000,
        }[tf]

    def test_1m_calendar_month_close(self):
        """1M candles must close at the 1st of the next calendar month 00:00:00 UTC."""
        # January 2026 (31 days)
        jan_start = int(datetime(2026, 1, 1, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        jan_close = get_candle_close_ms(self.mock_exchange, "1M", jan_start)
        expected_jan_close = int(datetime(2026, 2, 1, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        self.assertEqual(jan_close, expected_jan_close)

        # February 2024 (leap year, 29 days)
        feb_leap_start = int(datetime(2024, 2, 1, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        feb_leap_close = get_candle_close_ms(self.mock_exchange, "1M", feb_leap_start)
        expected_feb_close = int(datetime(2024, 3, 1, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        self.assertEqual(feb_leap_close, expected_feb_close)

        # December 2026 (year transition)
        dec_start = int(datetime(2026, 12, 1, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        dec_close = get_candle_close_ms(self.mock_exchange, "1M", dec_start)
        expected_dec_close = int(datetime(2027, 1, 1, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        self.assertEqual(dec_close, expected_dec_close)

    def test_resample_1m_to_1m_regression(self):
        """
        Regression Test:
        When downloading 2024-01 monthly candle on 2024-02-02 with --tf 1M --resample 1M,
        the closed 2024-01 candle must NOT be dropped.
        """
        dates = pd.date_range("2024-01-01", "2024-01-01", freq="MS", tz="UTC")
        df_raw = pd.DataFrame(
            {"open": 100, "high": 105, "low": 95, "close": 102, "volume": 1000},
            index=dates,
        )
        raw_last_dt = df_raw.index[-1]
        raw_last_ms = int(raw_last_dt.timestamp() * 1000)
        raw_last_close_ms = get_candle_close_ms(self.mock_exchange, "1M", raw_last_ms)

        df_res = resample_ohlcv(df_raw, "1M")
        bar_close_ms = get_resampled_bar_close_ms(
            df_res.index[-1], "1M", "1M", self.mock_exchange
        )

        # On 2024-02-02, January 2024 is already closed:
        now_feb2 = int(datetime(2024, 2, 2, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        should_drop = bar_close_ms > now_feb2 or bar_close_ms > raw_last_close_ms
        self.assertFalse(should_drop, "Closed 1M bar should NOT be dropped on 2024-02-02!")

        # On 2024-01-15, January 2024 is still in-progress:
        now_jan15 = int(datetime(2024, 1, 15, 0, 0, tzinfo=timezone.utc).timestamp() * 1000)
        should_drop_in_progress = bar_close_ms > now_jan15 or bar_close_ms > raw_last_close_ms
        self.assertTrue(
            should_drop_in_progress, "In-progress 1M bar MUST be dropped on 2024-01-15!"
        )

    def test_resample_daily_to_weekly_unclosed(self):
        """Daily data ending mid-week (e.g. Tuesday) must drop the unclosed weekly bar."""
        dates = pd.date_range("2026-08-31", "2026-09-08", freq="D", tz="UTC")  # Ends Tuesday
        df_raw = pd.DataFrame(
            {"open": 100, "high": 105, "low": 95, "close": 102, "volume": 1000},
            index=dates,
        )
        raw_last_dt = df_raw.index[-1]
        raw_last_ms = int(raw_last_dt.timestamp() * 1000)
        raw_last_close_ms = get_candle_close_ms(self.mock_exchange, "1d", raw_last_ms)

        df_res = resample_ohlcv(df_raw, "1W")
        self.assertEqual(len(df_res), 2)  # 2026-09-06 (closed) and 2026-09-13 (unclosed)

        bar_close_ms = get_resampled_bar_close_ms(
            df_res.index[-1], "1W", "1d", self.mock_exchange
        )
        now_sep9 = int(datetime(2026, 9, 9, 12, 0, tzinfo=timezone.utc).timestamp() * 1000)
        should_drop = bar_close_ms > now_sep9 or bar_close_ms > raw_last_close_ms
        self.assertTrue(should_drop, "Unclosed weekly bar must be dropped!")

        # Filter the unclosed bar
        if should_drop:
            df_res = df_res.iloc[:-1]

        self.assertEqual(len(df_res), 1)
        self.assertEqual(df_res.index[-1], pd.Timestamp("2026-09-06 00:00:00+00:00"))

    def test_resample_daily_to_3d_unclosed(self):
        """Daily data ending on day 1 of a 3-day bin must drop the unclosed 3D bar."""
        dates = pd.date_range("2026-09-01", "2026-09-08", freq="D", tz="UTC")
        df_raw = pd.DataFrame(
            {"open": 100, "high": 105, "low": 95, "close": 102, "volume": 1000},
            index=dates,
        )
        raw_last_dt = df_raw.index[-1]
        raw_last_ms = int(raw_last_dt.timestamp() * 1000)
        raw_last_close_ms = get_candle_close_ms(self.mock_exchange, "1d", raw_last_ms)

        df_res = resample_ohlcv(df_raw, "3D")
        bar_close_ms = get_resampled_bar_close_ms(
            df_res.index[-1], "3D", "1d", self.mock_exchange
        )
        now_sep9 = int(datetime(2026, 9, 9, 12, 0, tzinfo=timezone.utc).timestamp() * 1000)
        should_drop = bar_close_ms > now_sep9 or bar_close_ms > raw_last_close_ms
        self.assertTrue(should_drop, "Unclosed 3D bar must be dropped!")

        if should_drop:
            df_res = df_res.iloc[:-1]

        self.assertEqual(df_res.index[-1], pd.Timestamp("2026-09-07 00:00:00+00:00"))

    def test_resample_minute_to_15min_regression(self):
        """
        Regression Test:
        --tf 1m --resample 15min must NOT be mistaken for a month frequency (rule '15min').
        A completed 15-minute bar (00:01 to 00:15) closing at 00:16 UTC must NOT be dropped
        when evaluated after 00:16 UTC.
        """
        dates = pd.date_range("2026-09-09 00:01", "2026-09-09 00:15", freq="1min", tz="UTC")
        df_raw = pd.DataFrame(
            {"open": 100, "high": 105, "low": 95, "close": 102, "volume": 10},
            index=dates,
        )
        raw_last_dt = df_raw.index[-1]
        raw_last_ms = int(raw_last_dt.timestamp() * 1000)
        raw_last_close_ms = get_candle_close_ms(self.mock_exchange, "1m", raw_last_ms)

        df_res = resample_ohlcv(df_raw, "15min")
        bar_close_ms = get_resampled_bar_close_ms(
            df_res.index[-1], "15min", "1m", self.mock_exchange
        )

        bar_close_dt = pd.to_datetime(bar_close_ms, unit="ms", utc=True)
        self.assertEqual(bar_close_dt, pd.Timestamp("2026-09-09 00:16:00", tz="UTC"))

        # When evaluated after close (e.g. 00:20:00 UTC), it must NOT be dropped:
        now_after = int(datetime(2026, 9, 9, 0, 20, tzinfo=timezone.utc).timestamp() * 1000)
        should_drop_after = bar_close_ms > now_after or bar_close_ms > raw_last_close_ms
        self.assertFalse(should_drop_after, "Completed 15min bar must NOT be dropped!")

        # When evaluated during candle (e.g. 00:15:30 UTC), it MUST be dropped:
        now_during = int(datetime(2026, 9, 9, 0, 15, 30, tzinfo=timezone.utc).timestamp() * 1000)
        should_drop_during = bar_close_ms > now_during or bar_close_ms > raw_last_close_ms
        self.assertTrue(should_drop_during, "In-progress 15min bar MUST be dropped!")


if __name__ == "__main__":
    unittest.main()
